//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 04:24:19 PM EST 
//


package net.geni.www.resources.rspec.ext.sdx._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CephRbdContent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CephRbdContent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="size_gb" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mount_point" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CephRbdContent", propOrder = {
    "sizeGb",
    "mountPoint"
})
public class CephRbdContent {

    @XmlElement(name = "size_gb", required = true)
    protected String sizeGb;
    @XmlElement(name = "mount_point", required = true)
    protected String mountPoint;

    /**
     * Gets the value of the sizeGb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizeGb() {
        return sizeGb;
    }

    /**
     * Sets the value of the sizeGb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizeGb(String value) {
        this.sizeGb = value;
    }

    /**
     * Gets the value of the mountPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMountPoint() {
        return mountPoint;
    }

    /**
     * Sets the value of the mountPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMountPoint(String value) {
        this.mountPoint = value;
    }

}
