//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.16 at 12:11:22 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.geni.net/resources/rspec/ext/sdx/1/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.geni.www.resources.rspec.ext.sdx._1;
