//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.07 at 03:04:02 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.geni.net/resources/rspec/ext/sdx/1/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.geni.www.resources.rspec.ext.sdx._1;
